apiVersion: batch/v1
kind: CronJob
metadata:
  name: ccminiproject
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ccminiproject
              image: farhaane4/project
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
